name: CI

on:
  push:
    branches:
      - '**'
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  LANG: en_US.utf8
  RID: win-x64
  CONFIG: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            9

      - name: Download game assemblies from private repo
        run: ci/download-game-assemblies.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ASSEMBLIES_PAT }}
          GITHUB_REPO: ${{ secrets.GH_ASSEMBLIES_REPO }}

      - name: Restore
        run: dotnet restore -r ${{ env.RID }}

      - name: Build
        run: dotnet build -c ${{ env.CONFIG }} --no-restore

      - name: Test
        run: dotnet test -c ${{ env.CONFIG }} --no-build
        
      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: |
            ./src/**/bin
            ./src/**/obj
          key: ${{ runner.os }}-dotnet-build-${{ hashFiles('./src/**/bin/**') }}
  package:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ 'DealsSummary', 'CounterPriceButton' ]
    env:
      src_proj_path: src/ScehduleOneMods.${{ matrix.project }}/ScehduleOneMods.${{ matrix.project }}.csproj
      test_proj_path: tests/ScehduleOneMods.${{ matrix.project }}.Tests/ScehduleOneMods.${{ matrix.project }}.Tests.csproj
    steps:
      - name: Restore build output
        uses: actions/cache@v3
        with:
          path: |
            ./src/**/bin
            ./src/**/obj
          key: ${{ runner.os }}-dotnet-build-${{ hashFiles('./src/**/bin/**') }}

      - name: Version
        id: version
        shell: bash
        run: |
          version="$(grep -oPm1 "(?<=<VersionPrefix>)[^<]+" ${{ env.src_proj_path }})-ci$GITHUB_RUN_ID"
          echo "version-suffix=ci$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "release_name=schedule-one-mods_${{ matrix.project }}_v$version_${{ env.RID }}" >> $GITHUB_OUTPUT

      - name: Publish
        shell: bash
        run: ci/publish.sh ${{ matrix.project }} ${{ env.RID }} ${{ steps.version.outputs.release_name }} ${{ env.CONFIG }} ${{ steps.version.outputs.version-suffix }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: "artifacts/*${{ env.RID }}*/"