name: CI

on:
  push:
    branches:
      - '**'
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  LANG: en_US.utf8
  RID: win-x64
  CONFIG: Release
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      version_suffix: ci${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            9

      - name: Download game assemblies from private repo
        run: ci/download-game-assemblies.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ASSEMBLIES_PAT }}
          GITHUB_REPO: ${{ secrets.GH_ASSEMBLIES_REPO }}

      - name: Restore
        run: dotnet restore -r ${{ env.RID }}

      - name: Build
        run: dotnet build -c ${{ env.CONFIG }} --no-restore

      - name: Test
        run: dotnet test -c ${{ env.CONFIG }} --no-build

      - name: Publish
        shell: bash
        run: ci/publish-all.sh ${{ env.version_suffix }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: "artifacts/*${{ env.version_suffix  }}*/"