name: Publish

permissions:
  id-token: write
  contents: write
  attestations: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  BUILD_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install rename

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            9

      - name: Download game assemblies from private repo
        run: ci/download-game-assemblies.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ASSEMBLIES_PAT }}
          GITHUB_REPO: ${{ secrets.GH_ASSEMBLIES_REPO }}

      - name: Publish
        run: ./publish.sh
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/*
          retention-days: 1
          if-no-files-found: error

  release:
    name: Release
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Show files
        run: ls -R
      
      - name: Create Checksums
        run: ci/checksums.sh

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-checksums: artifacts/shasum.txt
  
      - name: Create Release Notes
        run: ci/release-notes.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body_path: release-notes.md
          files: |
            artifacts/schedule-one-mods*
            artifacts/shasum.txt          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
