name: Publish

permissions:
  id-token: write
  contents: write
  attestations: write

on:
  push:
    tags:
      - "*-v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            9

      - name: Download game assemblies from private repo
        run: ci/download-game-assemblies.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ASSEMBLIES_PAT }}
          GITHUB_REPO: ${{ secrets.GH_ASSEMBLIES_REPO }}

      - name: Publish
        run: ./publish.sh
  
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/*
          retention-days: 1
          if-no-files-found: error

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Show files
        run: ls -R

      - name: Create Checksums
        run: ci/checksums.sh

      - name: Generate artifact attestation
        id: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-checksums: artifacts/shasum.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-shasum
          path: artifacts/shasum.txt
          retention-days: 1
          if-no-files-found: error

      - name: Create job outputs
        id: job-info
        env:
          GH_TOKEN: ${{ github.token }}
        run: ci/create-job-outputs.sh >> $GITHUB_OUTPUT
    outputs:
      attestation_url: ${{ steps.attest.outputs.attestation-url }}
      checksum_url: ${{ steps.job-info.outputs.checksum_url }}
      job_id: ${{ steps.job-info.outputs.job_id }}
  
  archive-job-log:
    name: Archive Job Log
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Archive
        id: archive
        env:
          GH_TOKEN: ${{ github.token }}
        run: ci/archive-job-log.sh ${{ needs.publish.outputs.job_id }} >> $GITHUB_OUTPUT
    outputs:
      archived_job_url: ${{ steps.archive.outputs.archived_url }}
          
  release-github:
    name: Release Github
    needs: [publish, archive-job-log]
    if: needs.publish.result == 'success' && needs.archive-job-log.result != 'cancelled'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release Notes 
        env:
          ATTESTATION_URL: ${{ needs.publish.outputs.attestation_url }}
          CHECKSUM_URL: ${{ needs.publish.outputs.checksum_url }}
          ARCHIVED_JOB_URL: ${{ needs.archive-job-log.outputs.archived_job_url }}
        run: ci/release-notes.sh > release-notes.md

      - name: Show files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body_path: release-notes.md
          files: |
            artifacts/schedule-one-mods*
            artifacts/shasum.txt          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  release-nexus:
    name: Release Nexusmods
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Release
        run: ci/release-nexus.sh ${{ github.ref_name }}
        env:
          UNEX_APIKEY: ${{ secrets.NEXUS_API_KEY }}
          UNEX_SESSION_COOKIE: ${{ secrets.NEXUS_SESSION_COOKIE }}